// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "tri_intersect.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic tri_intersect::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic tri_intersect::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> tri_intersect::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> tri_intersect::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> tri_intersect::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> tri_intersect::ap_const_lv1_1 = "1";
const sc_lv<32> tri_intersect::ap_const_lv32_1 = "1";

tri_intersect::tri_intersect(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_bdd_37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_56);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_37 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_56 );

    SC_METHOD(thread_ap_sig_ioackin_outs_TREADY);
    sensitive << ( outs_TREADY );
    sensitive << ( ap_reg_ioackin_outs_TREADY );

    SC_METHOD(thread_ins_TREADY);
    sensitive << ( ins_TVALID );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_ioackin_outs_TREADY );

    SC_METHOD(thread_outs_TDATA);
    sensitive << ( ins_TDATA );
    sensitive << ( ins_TVALID );
    sensitive << ( ins_data_V_val_reg_132 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TDEST);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TDEST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TID);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TKEEP);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TKEEP );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TLAST);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TLAST );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TSTRB);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TSTRB );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TUSER);
    sensitive << ( ins_TVALID );
    sensitive << ( ins_TUSER );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_outs_TVALID);
    sensitive << ( ins_TVALID );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_reg_ioackin_outs_TREADY );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ins_TVALID );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_ioackin_outs_TREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    ap_reg_ioackin_outs_TREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "tri_intersect_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, ins_TDATA, "(port)ins_TDATA");
    sc_trace(mVcdFile, ins_TVALID, "(port)ins_TVALID");
    sc_trace(mVcdFile, ins_TREADY, "(port)ins_TREADY");
    sc_trace(mVcdFile, ins_TKEEP, "(port)ins_TKEEP");
    sc_trace(mVcdFile, ins_TSTRB, "(port)ins_TSTRB");
    sc_trace(mVcdFile, ins_TUSER, "(port)ins_TUSER");
    sc_trace(mVcdFile, ins_TLAST, "(port)ins_TLAST");
    sc_trace(mVcdFile, ins_TID, "(port)ins_TID");
    sc_trace(mVcdFile, ins_TDEST, "(port)ins_TDEST");
    sc_trace(mVcdFile, outs_TDATA, "(port)outs_TDATA");
    sc_trace(mVcdFile, outs_TVALID, "(port)outs_TVALID");
    sc_trace(mVcdFile, outs_TREADY, "(port)outs_TREADY");
    sc_trace(mVcdFile, outs_TKEEP, "(port)outs_TKEEP");
    sc_trace(mVcdFile, outs_TSTRB, "(port)outs_TSTRB");
    sc_trace(mVcdFile, outs_TUSER, "(port)outs_TUSER");
    sc_trace(mVcdFile, outs_TLAST, "(port)outs_TLAST");
    sc_trace(mVcdFile, outs_TID, "(port)outs_TID");
    sc_trace(mVcdFile, outs_TDEST, "(port)outs_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ins_data_V_val_reg_132, "ins_data_V_val_reg_132");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_37, "ap_sig_bdd_37");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_56, "ap_sig_bdd_56");
    sc_trace(mVcdFile, ap_sig_ioackin_outs_TREADY, "ap_sig_ioackin_outs_TREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_outs_TREADY, "ap_reg_ioackin_outs_TREADY");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("tri_intersect.hdltvin.dat");
    mHdltvoutHandle.open("tri_intersect.hdltvout.dat");
}

tri_intersect::~tri_intersect() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void tri_intersect::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_outs_TREADY = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
              !(esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outs_TREADY.read()))))) {
            ap_reg_ioackin_outs_TREADY = ap_const_logic_0;
        } else if (((!esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, outs_TREADY.read())))) {
            ap_reg_ioackin_outs_TREADY = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0))) {
        ins_data_V_val_reg_132 = ins_TDATA.read();
    }
}

void tri_intersect::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void tri_intersect::thread_ap_sig_bdd_37() {
    ap_sig_bdd_37 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void tri_intersect::thread_ap_sig_bdd_56() {
    ap_sig_bdd_56 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void tri_intersect::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_37.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void tri_intersect::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_56.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void tri_intersect::thread_ap_sig_ioackin_outs_TREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_outs_TREADY.read())) {
        ap_sig_ioackin_outs_TREADY = outs_TREADY.read();
    } else {
        ap_sig_ioackin_outs_TREADY = ap_const_logic_1;
    }
}

void tri_intersect::thread_ins_TREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !(esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outs_TREADY.read()))))) {
        ins_TREADY = ap_const_logic_1;
    } else {
        ins_TREADY = ap_const_logic_0;
    }
}

void tri_intersect::thread_outs_TDATA() {
    outs_TDATA = (!ins_TDATA.read().is_01() || !ins_data_V_val_reg_132.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ins_TDATA.read()) + sc_biguint<32>(ins_data_V_val_reg_132.read()));
}

void tri_intersect::thread_outs_TDEST() {
    outs_TDEST = ins_TDEST.read();
}

void tri_intersect::thread_outs_TID() {
    outs_TID = ins_TID.read();
}

void tri_intersect::thread_outs_TKEEP() {
    outs_TKEEP = ins_TKEEP.read();
}

void tri_intersect::thread_outs_TLAST() {
    outs_TLAST = ins_TLAST.read();
}

void tri_intersect::thread_outs_TSTRB() {
    outs_TSTRB = ins_TSTRB.read();
}

void tri_intersect::thread_outs_TUSER() {
    outs_TUSER = ins_TUSER.read();
}

void tri_intersect::thread_outs_TVALID() {
    if (((!esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_outs_TREADY.read())))) {
        outs_TVALID = ap_const_logic_1;
    } else {
        outs_TVALID = ap_const_logic_0;
    }
}

void tri_intersect::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!(esl_seteq<1,1,1>(ins_TVALID.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_outs_TREADY.read()))) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void tri_intersect::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TDATA\" :  \"" << ins_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TVALID\" :  \"" << ins_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ins_TREADY\" :  \"" << ins_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TKEEP\" :  \"" << ins_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TSTRB\" :  \"" << ins_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TUSER\" :  \"" << ins_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TLAST\" :  \"" << ins_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TID\" :  \"" << ins_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ins_TDEST\" :  \"" << ins_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TDATA\" :  \"" << outs_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TVALID\" :  \"" << outs_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outs_TREADY\" :  \"" << outs_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TKEEP\" :  \"" << outs_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TSTRB\" :  \"" << outs_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TUSER\" :  \"" << outs_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TLAST\" :  \"" << outs_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TID\" :  \"" << outs_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outs_TDEST\" :  \"" << outs_TDEST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

