lappend pragmaStatus0 {pragma "INTERFACE" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "UNROLL" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect/LOAD" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'LOAD' does not exist in function 'tri_intersect'. "}
lappend pragmaStatus4 {pragma "UNROLL" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect/READ" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect/WORK" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "UNROLL" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect/WRITE" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v1x"}
lappend pragmaStatus8 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v0y"}
lappend pragmaStatus9 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v0x"}
lappend pragmaStatus10 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v2z"}
lappend pragmaStatus11 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rez"}
lappend pragmaStatus12 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "beta"}
lappend pragmaStatus13 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v1z"}
lappend pragmaStatus14 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "t"}
lappend pragmaStatus15 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v1y"}
lappend pragmaStatus16 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rey"}
lappend pragmaStatus17 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rdy"}
lappend pragmaStatus18 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rdx"}
lappend pragmaStatus19 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v2x"}
lappend pragmaStatus20 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rex"}
lappend pragmaStatus21 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v0z"}
lappend pragmaStatus22 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "v2y"}
lappend pragmaStatus23 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "rdz"}
lappend pragmaStatus24 {pragma "ARRAY_MAP" source "C:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect.cpp" location "tri_intersect" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "gamma"}
