# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/triangle_intersect/triangle_intersect.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect || ORIG_REF_NAME==triangle_intersect}]

# IP: bd/triangle_intersect/ip/triangle_intersect_processing_system7_0_0/triangle_intersect_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_processing_system7_0_0 || ORIG_REF_NAME==triangle_intersect_processing_system7_0_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_axi_dma_0_0 || ORIG_REF_NAME==triangle_intersect_axi_dma_0_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_processing_system7_0_axi_periph_0/triangle_intersect_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==triangle_intersect_processing_system7_0_axi_periph_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_axi_mem_intercon_0/triangle_intersect_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_axi_mem_intercon_0 || ORIG_REF_NAME==triangle_intersect_axi_mem_intercon_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_xbar_0/triangle_intersect_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_xbar_0 || ORIG_REF_NAME==triangle_intersect_xbar_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_xlconcat_0_0/triangle_intersect_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_xlconcat_0_0 || ORIG_REF_NAME==triangle_intersect_xlconcat_0_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_tri_intersect_0_1/triangle_intersect_tri_intersect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_tri_intersect_0_1 || ORIG_REF_NAME==triangle_intersect_tri_intersect_0_1}]

# IP: bd/triangle_intersect/ip/triangle_intersect_auto_pc_0/triangle_intersect_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_pc_0 || ORIG_REF_NAME==triangle_intersect_auto_pc_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_auto_pc_1/triangle_intersect_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_pc_1 || ORIG_REF_NAME==triangle_intersect_auto_pc_1}]

# IP: bd/triangle_intersect/ip/triangle_intersect_auto_us_0/triangle_intersect_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_0 || ORIG_REF_NAME==triangle_intersect_auto_us_0}]

# IP: bd/triangle_intersect/ip/triangle_intersect_auto_us_1/triangle_intersect_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_1 || ORIG_REF_NAME==triangle_intersect_auto_us_1}]

# IP: bd/triangle_intersect/ip/triangle_intersect_auto_us_2/triangle_intersect_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_2 || ORIG_REF_NAME==triangle_intersect_auto_us_2}]

# XDC: bd/triangle_intersect/ip/triangle_intersect_processing_system7_0_0/triangle_intersect_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_processing_system7_0_0 || ORIG_REF_NAME==triangle_intersect_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_axi_dma_0_0 || ORIG_REF_NAME==triangle_intersect_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_axi_dma_0_0 || ORIG_REF_NAME==triangle_intersect_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0}]

# XDC: bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==triangle_intersect_rst_processing_system7_0_100M_0}]

# XDC: bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_xbar_0/triangle_intersect_xbar_0_ooc.xdc

# XDC: ipshared/xilinx.com/tri_intersect_v0_1/a5e4dcf8/constraints/tri_intersect_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_pc_0/triangle_intersect_auto_pc_0_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_pc_1/triangle_intersect_auto_pc_1_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_0/triangle_intersect_auto_us_0_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_0/triangle_intersect_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_0 || ORIG_REF_NAME==triangle_intersect_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_1/triangle_intersect_auto_us_1_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_1/triangle_intersect_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_1 || ORIG_REF_NAME==triangle_intersect_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_2/triangle_intersect_auto_us_2_ooc.xdc

# XDC: bd/triangle_intersect/ip/triangle_intersect_auto_us_2/triangle_intersect_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==triangle_intersect_auto_us_2 || ORIG_REF_NAME==triangle_intersect_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/triangle_intersect/triangle_intersect_ooc.xdc
