# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.cache/wt [current_project]
set_property parent.project_path C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/Justin/Documents/GitHub/fpga-trace/hls/triangle_intersect/tri_intersect/impl/ip [current_project]
add_files C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/triangle_intersect.bd
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_processing_system7_0_0/triangle_intersect_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_axi_dma_0_0/triangle_intersect_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_rst_processing_system7_0_100M_0/triangle_intersect_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_xbar_0/triangle_intersect_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/ipshared/xilinx.com/tri_intersect_v0_1/a5e4dcf8/constraints/tri_intersect_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_pc_0/triangle_intersect_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_pc_1/triangle_intersect_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_0/triangle_intersect_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_0/triangle_intersect_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_1/triangle_intersect_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_1/triangle_intersect_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_2/triangle_intersect_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/ip/triangle_intersect_auto_us_2/triangle_intersect_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/triangle_intersect_ooc.xdc]
set_property is_locked true [get_files C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/triangle_intersect.bd]

read_vhdl -library xil_defaultlib C:/Users/Justin/Documents/GitHub/fpga-trace/design/raytracer_design.srcs/sources_1/bd/triangle_intersect/hdl/triangle_intersect_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top triangle_intersect_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef triangle_intersect_wrapper.dcp
catch { report_utilization -file triangle_intersect_wrapper_utilization_synth.rpt -pb triangle_intersect_wrapper_utilization_synth.pb }
